---
- name: Show IP DHCP Bind
  hosts: router
  gather_facts: false
  connection: network_cli

  tasks: 
  - name: Show IP DHCP Bind
    ios_command:
      commands: show ip dhcp bind
    register: output

  - name: Print Output (Router)
    debug:
      var: output.stdout_lines

  - name: Save my_output to a file on disk
    copy: # copy module
        content: "{{output.stdout[0]}}" # Output content
        dest: "/home/justin/{{inventory_hostname}}_DHCP_Bind.txt"
...
