---
- name: Add VLANs
  hosts: Routers
  gather_facts: false
  connection: network_cli
  collections:
    - cisco.ios:
  
  tasks:
    - name: Add VLANs
      cisco.ios.ios_vlans:
        config:
          - name: Network_Management
            vlan_id: 10
            state: active
            shutdown: enabled
        state: merged
...
