---
- name: IOS XR Show Version
  hosts: iosxr
  gather_facts: false
  connection: network_cli

  tasks:
  - name: Show Version
    iosxr_command:
      commands: show version
    register: output

  - name: Save ouput
    debug:
      var: output.stdout_lines
...
